const WORD_LIST = [
  // Animals
  { word: 'Elephant', related: 'Penguin', category: 'Animals' },
  { word: 'Penguin', related: 'Dolphin', category: 'Animals' },
  { word: 'Dolphin', related: 'Giraffe', category: 'Animals' },
  { word: 'Giraffe', related: 'Kangaroo', category: 'Animals' },
  { word: 'Kangaroo', related: 'Octopus', category: 'Animals' },
  { word: 'Octopus', related: 'Chameleon', category: 'Animals' },
  { word: 'Chameleon', related: 'Flamingo', category: 'Animals' },
  { word: 'Flamingo', related: 'Hedgehog', category: 'Animals' },
  { word: 'Hedgehog', related: 'Peacock', category: 'Animals' },
  { word: 'Peacock', related: 'Hamster', category: 'Animals' },
  { word: 'Hamster', related: 'Jellyfish', category: 'Animals' },
  { word: 'Jellyfish', related: 'Parrot', category: 'Animals' },
  { word: 'Parrot', related: 'Koala', category: 'Animals' },
  { word: 'Koala', related: 'Cheetah', category: 'Animals' },
  { word: 'Cheetah', related: 'Elephant', category: 'Animals' },

  // Food
  { word: 'Pizza', related: 'Sushi', category: 'Food' },
  { word: 'Sushi', related: 'Pancake', category: 'Food' },
  { word: 'Pancake', related: 'Taco', category: 'Food' },
  { word: 'Taco', related: 'Chocolate', category: 'Food' },
  { word: 'Chocolate', related: 'Croissant', category: 'Food' },
  { word: 'Croissant', related: 'Avocado', category: 'Food' },
  { word: 'Avocado', related: 'Popcorn', category: 'Food' },
  { word: 'Popcorn', related: 'Waffle', category: 'Food' },
  { word: 'Waffle', related: 'Burrito', category: 'Food' },
  { word: 'Burrito', related: 'Donut', category: 'Food' },
  { word: 'Donut', related: 'Lasagna', category: 'Food' },
  { word: 'Lasagna', related: 'Pretzel', category: 'Food' },
  { word: 'Pretzel', related: 'Mango', category: 'Food' },
  { word: 'Mango', related: 'Dumpling', category: 'Food' },
  { word: 'Dumpling', related: 'Pizza', category: 'Food' },

  // Places
  { word: 'Beach', related: 'Library', category: 'Places' },
  { word: 'Library', related: 'Hospital', category: 'Places' },
  { word: 'Hospital', related: 'Airport', category: 'Places' },
  { word: 'Airport', related: 'Museum', category: 'Places' },
  { word: 'Museum', related: 'Volcano', category: 'Places' },
  { word: 'Volcano', related: 'Lighthouse', category: 'Places' },
  { word: 'Lighthouse', related: 'Castle', category: 'Places' },
  { word: 'Castle', related: 'Aquarium', category: 'Places' },
  { word: 'Aquarium', related: 'Subway', category: 'Places' },
  { word: 'Subway', related: 'Jungle', category: 'Places' },
  { word: 'Jungle', related: 'Bakery', category: 'Places' },
  { word: 'Bakery', related: 'Stadium', category: 'Places' },
  { word: 'Stadium', related: 'Carnival', category: 'Places' },
  { word: 'Carnival', related: 'Igloo', category: 'Places' },
  { word: 'Igloo', related: 'Beach', category: 'Places' },

  // Objects
  { word: 'Umbrella', related: 'Telescope', category: 'Objects' },
  { word: 'Telescope', related: 'Typewriter', category: 'Objects' },
  { word: 'Typewriter', related: 'Chandelier', category: 'Objects' },
  { word: 'Chandelier', related: 'Trampoline', category: 'Objects' },
  { word: 'Trampoline', related: 'Compass', category: 'Objects' },
  { word: 'Compass', related: 'Saxophone', category: 'Objects' },
  { word: 'Saxophone', related: 'Binoculars', category: 'Objects' },
  { word: 'Binoculars', related: 'Hammock', category: 'Objects' },
  { word: 'Hammock', related: 'Suitcase', category: 'Objects' },
  { word: 'Suitcase', related: 'Candle', category: 'Objects' },
  { word: 'Candle', related: 'Boomerang', category: 'Objects' },
  { word: 'Boomerang', related: 'Trophy', category: 'Objects' },
  { word: 'Trophy', related: 'Snowglobe', category: 'Objects' },
  { word: 'Snowglobe', related: 'Headphones', category: 'Objects' },
  { word: 'Headphones', related: 'Umbrella', category: 'Objects' },

  // Sports
  { word: 'Basketball', related: 'Surfing', category: 'Sports' },
  { word: 'Surfing', related: 'Fencing', category: 'Sports' },
  { word: 'Fencing', related: 'Gymnastics', category: 'Sports' },
  { word: 'Gymnastics', related: 'Archery', category: 'Sports' },
  { word: 'Archery', related: 'Skateboarding', category: 'Sports' },
  { word: 'Skateboarding', related: 'Volleyball', category: 'Sports' },
  { word: 'Volleyball', related: 'Wrestling', category: 'Sports' },
  { word: 'Wrestling', related: 'Cricket', category: 'Sports' },
  { word: 'Cricket', related: 'Bowling', category: 'Sports' },
  { word: 'Bowling', related: 'Snowboarding', category: 'Sports' },
  { word: 'Snowboarding', related: 'Boxing', category: 'Sports' },
  { word: 'Boxing', related: 'Karate', category: 'Sports' },
  { word: 'Karate', related: 'Badminton', category: 'Sports' },
  { word: 'Badminton', related: 'Rowing', category: 'Sports' },
  { word: 'Rowing', related: 'Basketball', category: 'Sports' },

  // Nature
  { word: 'Waterfall', related: 'Rainbow', category: 'Nature' },
  { word: 'Rainbow', related: 'Tornado', category: 'Nature' },
  { word: 'Tornado', related: 'Glacier', category: 'Nature' },
  { word: 'Glacier', related: 'Coral Reef', category: 'Nature' },
  { word: 'Coral Reef', related: 'Aurora', category: 'Nature' },
  { word: 'Aurora', related: 'Cactus', category: 'Nature' },
  { word: 'Cactus', related: 'Mushroom', category: 'Nature' },
  { word: 'Mushroom', related: 'Sunflower', category: 'Nature' },
  { word: 'Sunflower', related: 'Lightning', category: 'Nature' },
  { word: 'Lightning', related: 'Earthquake', category: 'Nature' },
  { word: 'Earthquake', related: 'Avalanche', category: 'Nature' },
  { word: 'Avalanche', related: 'Bamboo', category: 'Nature' },
  { word: 'Bamboo', related: 'Sandstorm', category: 'Nature' },
  { word: 'Sandstorm', related: 'Eclipse', category: 'Nature' },
  { word: 'Eclipse', related: 'Waterfall', category: 'Nature' },

  // Professions
  { word: 'Astronaut', related: 'Detective', category: 'Professions' },
  { word: 'Detective', related: 'Lifeguard', category: 'Professions' },
  { word: 'Lifeguard', related: 'Magician', category: 'Professions' },
  { word: 'Magician', related: 'Blacksmith', category: 'Professions' },
  { word: 'Blacksmith', related: 'Pilot', category: 'Professions' },
  { word: 'Pilot', related: 'Photographer', category: 'Professions' },
  { word: 'Photographer', related: 'Firefighter', category: 'Professions' },
  { word: 'Firefighter', related: 'Archaeologist', category: 'Professions' },
  { word: 'Archaeologist', related: 'Veterinarian', category: 'Professions' },
  { word: 'Veterinarian', related: 'Chef', category: 'Professions' },
  { word: 'Chef', related: 'Surgeon', category: 'Professions' },
  { word: 'Surgeon', related: 'Librarian', category: 'Professions' },
  { word: 'Librarian', related: 'Plumber', category: 'Professions' },
  { word: 'Plumber', related: 'Electrician', category: 'Professions' },
  { word: 'Electrician', related: 'Astronaut', category: 'Professions' },

]; 

export function getRandomWord() {
  const index = Math.floor(Math.random() * WORD_LIST.length);
  return WORD_LIST[index];
}

export default WORD_LIST;
