const WORD_LIST = [
  // Animals
  { word: 'Elephant', category: 'Animals' },
  { word: 'Penguin', category: 'Animals' },
  { word: 'Dolphin', category: 'Animals' },
  { word: 'Giraffe', category: 'Animals' },
  { word: 'Kangaroo', category: 'Animals' },
  { word: 'Octopus', category: 'Animals' },
  { word: 'Chameleon', category: 'Animals' },
  { word: 'Flamingo', category: 'Animals' },
  { word: 'Hedgehog', category: 'Animals' },
  { word: 'Peacock', category: 'Animals' },
  { word: 'Hamster', category: 'Animals' },
  { word: 'Jellyfish', category: 'Animals' },
  { word: 'Parrot', category: 'Animals' },
  { word: 'Koala', category: 'Animals' },
  { word: 'Cheetah', category: 'Animals' },

  // Food
  { word: 'Pizza', category: 'Food' },
  { word: 'Sushi', category: 'Food' },
  { word: 'Pancake', category: 'Food' },
  { word: 'Taco', category: 'Food' },
  { word: 'Chocolate', category: 'Food' },
  { word: 'Croissant', category: 'Food' },
  { word: 'Avocado', category: 'Food' },
  { word: 'Popcorn', category: 'Food' },
  { word: 'Waffle', category: 'Food' },
  { word: 'Burrito', category: 'Food' },
  { word: 'Donut', category: 'Food' },
  { word: 'Lasagna', category: 'Food' },
  { word: 'Pretzel', category: 'Food' },
  { word: 'Mango', category: 'Food' },
  { word: 'Dumpling', category: 'Food' },

  // Places
  { word: 'Beach', category: 'Places' },
  { word: 'Library', category: 'Places' },
  { word: 'Hospital', category: 'Places' },
  { word: 'Airport', category: 'Places' },
  { word: 'Museum', category: 'Places' },
  { word: 'Volcano', category: 'Places' },
  { word: 'Lighthouse', category: 'Places' },
  { word: 'Castle', category: 'Places' },
  { word: 'Aquarium', category: 'Places' },
  { word: 'Subway', category: 'Places' },
  { word: 'Jungle', category: 'Places' },
  { word: 'Bakery', category: 'Places' },
  { word: 'Stadium', category: 'Places' },
  { word: 'Carnival', category: 'Places' },
  { word: 'Igloo', category: 'Places' },

  // Objects
  { word: 'Umbrella', category: 'Objects' },
  { word: 'Telescope', category: 'Objects' },
  { word: 'Typewriter', category: 'Objects' },
  { word: 'Chandelier', category: 'Objects' },
  { word: 'Trampoline', category: 'Objects' },
  { word: 'Compass', category: 'Objects' },
  { word: 'Saxophone', category: 'Objects' },
  { word: 'Binoculars', category: 'Objects' },
  { word: 'Hammock', category: 'Objects' },
  { word: 'Suitcase', category: 'Objects' },
  { word: 'Candle', category: 'Objects' },
  { word: 'Boomerang', category: 'Objects' },
  { word: 'Trophy', category: 'Objects' },
  { word: 'Snowglobe', category: 'Objects' },
  { word: 'Headphones', category: 'Objects' },

  // Sports
  { word: 'Basketball', category: 'Sports' },
  { word: 'Surfing', category: 'Sports' },
  { word: 'Fencing', category: 'Sports' },
  { word: 'Gymnastics', category: 'Sports' },
  { word: 'Archery', category: 'Sports' },
  { word: 'Skateboarding', category: 'Sports' },
  { word: 'Volleyball', category: 'Sports' },
  { word: 'Wrestling', category: 'Sports' },
  { word: 'Cricket', category: 'Sports' },
  { word: 'Bowling', category: 'Sports' },
  { word: 'Snowboarding', category: 'Sports' },
  { word: 'Boxing', category: 'Sports' },
  { word: 'Karate', category: 'Sports' },
  { word: 'Badminton', category: 'Sports' },
  { word: 'Rowing', category: 'Sports' },

  // Nature
  { word: 'Waterfall', category: 'Nature' },
  { word: 'Rainbow', category: 'Nature' },
  { word: 'Tornado', category: 'Nature' },
  { word: 'Glacier', category: 'Nature' },
  { word: 'Coral Reef', category: 'Nature' },
  { word: 'Aurora', category: 'Nature' },
  { word: 'Cactus', category: 'Nature' },
  { word: 'Mushroom', category: 'Nature' },
  { word: 'Sunflower', category: 'Nature' },
  { word: 'Lightning', category: 'Nature' },
  { word: 'Earthquake', category: 'Nature' },
  { word: 'Avalanche', category: 'Nature' },
  { word: 'Bamboo', category: 'Nature' },
  { word: 'Sandstorm', category: 'Nature' },
  { word: 'Eclipse', category: 'Nature' },

  // Professions
  { word: 'Astronaut', category: 'Professions' },
  { word: 'Detective', category: 'Professions' },
  { word: 'Lifeguard', category: 'Professions' },
  { word: 'Magician', category: 'Professions' },
  { word: 'Blacksmith', category: 'Professions' },
  { word: 'Pilot', category: 'Professions' },
  { word: 'Photographer', category: 'Professions' },
  { word: 'Firefighter', category: 'Professions' },
  { word: 'Archaeologist', category: 'Professions' },
  { word: 'Veterinarian', category: 'Professions' },
  { word: 'Chef', category: 'Professions' },
  { word: 'Surgeon', category: 'Professions' },
  { word: 'Librarian', category: 'Professions' },
  { word: 'Plumber', category: 'Professions' },
  { word: 'Electrician', category: 'Professions' },
];

export function getRandomWord() {
  const index = Math.floor(Math.random() * WORD_LIST.length);
  return WORD_LIST[index];
}

export default WORD_LIST;
